name: eclass_api
description: Dart client for the Open eClass Platform mobile API.
version: 1.0.1
repository: https://github.com/georgiadisc/eclass_api

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  html: ^0.15.0
  http: ^0.13.4
  xml: ^6.0.1
